### ISSUE TITLE
Uncaught TypeError: _this.zoomOut is not a function

### ISSUE THREAD

**Issue by frisbi01** [trompamusic/mei-friend#12]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.58.0 x64
**Electron**: 9.4.4
**OS**: macOS 12.0.1
**Thrown From**: [mei-friend](https://github.com/trompamusic/mei-friend) package 0.5.2

### Stack Trace

Uncaught TypeError: _this.zoomOut is not a function

```
At /Users/frisbi01/.atom/packages/mei-friend/lib/mei-friend-view.js:120

TypeError: _this.zoomOut is not a function
    at /packages/mei-friend/lib/mei-friend-view.js:120:16)
    at HTMLButtonElement.dispatch (/packages/mei-friend/node_modules/jquery/dist/jquery.js:5430:27)
    at HTMLButtonElement.elemData.handle (/packages/mei-friend/node_modules/jquery/dist/jquery.js:5234:28)
```

### Commands

```
```

### Non-Core Packages

```
language-mei 0.34.5 
mei-friend 0.5.2 
```

**Comment by wergo** [comment]
Thanks for spotting this. Fixed in mei-friend 0.5.3
