### ISSUE TITLE
Configure file extension support

### ISSUE THREAD

**Issue by rettinghaus** [trompamusic/mei-friend#3]
At the moment the file to be rendered has to be explicitly a `*.mei` file. But not every project uses `mei` as extension but `xml`.

**Comment by wergo** [comment]
Would adding the extension `.xml` suffice?

**Comment by rettinghaus** [comment]
Basically yes (at least for me right now). But maybe someone has other needs, so making it configurable would be a nice touch.

**Comment by wergo** [comment]
https://github.com/trompamusic/mei-friend/commit/d52010ff3b29e863d34d3db639f20136ffc24373 (MEI-friend 0.2.15) scans encoding for `<mei` tag to decide on whether it's a MEI file or not, rather than to rely on the file extension `.mei`.

**Comment by rettinghaus** [comment]
Thanks!
