### ISSUE TITLE
Add dropdown for fonts

### ISSUE THREAD

**Issue by rettinghaus** [trompamusic/mei-friend#6]
It would be nice if you could switch between the different fonts that come with Verovio.

**Comment by wergo** [comment]
Good idea.

**Comment by wergo** [comment]
Addressed in https://github.com/trompamusic/mei-friend/releases/tag/v0.3.3

**Comment by wergo** [comment]
@rettinghaus Is there a way to also set the normal font, such as for directives etc.?

**Comment by rettinghaus** [comment]
@wergo Currently in upstream toolkit there is no way to do this, as the text font bounding boxes are "hard coded" for Times.
