### ISSUE TITLE
Allow del key to easily delete items

### ISSUE THREAD

**Issue by rettinghaus** [trompamusic/mei-friend#7]
It would be convenient if you could delete items as easy as you could add them.

**Comment by wergo** [comment]
Addressed in https://github.com/trompamusic/mei-friend/commit/15eb3ecff5253470580c91a125ac555d3da7a003 for `control elements`, `clef`, `accid`, and `artic`; the latter two only if encoded as elements. 

Currently both `BACKSPACE` and `DELETE` work. Any preference for these?

**Comment by rettinghaus** [comment]
I like both, so I don't mind. Leave it like that until the next one complains.
