### ISSUE TITLE
Undesired code changes

### ISSUE THREAD

**Issue by o-sapov** [trompamusic/mei-friend#9]
When performing MEI manipulation, e. g. _invert att.placement_, additional code changes are performed:

1. Schema is replaced

<img width="1232" alt="mei_friend_schema" src="https://user-images.githubusercontent.com/24490898/114353843-c859c900-9b6d-11eb-8fb0-d8e571c6acbd.png">

2. Entities are resolved
<img width="719" alt="resolves_entities" src="https://user-images.githubusercontent.com/24490898/114353938-e1fb1080-9b6d-11eb-9aee-43712f3aaeea.png">
3. facsimile is deleted

<img width="955" alt="del_facsimile" src="https://user-images.githubusercontent.com/24490898/114354196-2edee700-9b6e-11eb-8a40-696f9edd6e37.png">

4. @tstamps get trailing zeros (not for all elements):
<img width="722" alt="tstamp" src="https://user-images.githubusercontent.com/24490898/114354236-39997c00-9b6e-11eb-834f-b4c18d081b94.png">

MEI:
```xml<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="../../schemas/mei-DME-4.0.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<?xml-model href="../../schemas/mei-DME-4.0.rng" type="application/xml" schematypens="http://purl.oclc.org/dsdl/schematron"?>
<mei meiversion="4.0.1" xmlns="http://www.music-encoding.org/ns/mei">
  <meiHead>
    <fileDesc>
      <titleStmt>
        <title>MRE</title>
      </titleStmt>
      <encodingDesc>
        <editorialDecl label="Editor’s Note" xml:lang="EN">
          <p>&#160;&#160; - Autograph thematic catalog (NMA siglum A<rend rend="sup">1</rend>)</p>
          <p>&#160;&#160; - Dedication copy (NMA siglum A<rend rend="sup">2</rend>)</p>
          <p>&#160;&#160; - First print edition, Artaria &amp; Co. Vienna (1785) (NMA siglum B<rend rend="sup">1</rend>)</p>
          <p>&#160;&#160; - First print edition, Artaria &amp; Co. Vienna, 2nd copy (NMA siglum B<rend rend="sup">2</rend>)</p>
          <p>&#160;&#160; - First print edition, Artaria &amp; Co. Vienna, 3rd-6th copy (NMA siglum B<rend rend="sup">3</rend>)</p>
          <p>&#160;&#160; - First print edition, Artaria &amp; Co. Vienna, 7th copy, entirely new engraved (NMA siglum B<rend rend="sup">4</rend>)</p>
          <p>&#160;&#160; - Early print edition, Breitkopf &amp; Härtel (1799) (NMA siglum C)</p>
          <p>&#160;&#160; - Early print edition, Johann André Offenbach am Main (1802) (NMA siglum D<rend rend="sup">1</rend>)</p>
          <p>&#160;&#160; - Early print edition, Johann André Offenbach am Main (c. 1829) (NMA siglum D<rend rend="sup">2</rend>)</p>
          <p>&#160;&#160; - Early print edition, Johann André Offenbach am Main (1841) (NMA siglum D<rend rend="sup">3</rend>)</p>
          <p>&#160;&#160; - Early print edition, Johann André Offenbach am Main (probably after 1841) (NMA siglum D<rend rend="sup">4</rend>)</p>
        </editorialDecl>
      </encodingDesc>
      <pubStmt/>
    </fileDesc>
  </meiHead>
  <facsimile>
    <surface label="91" xml:id="surface_91">
      <graphic target="page91.tif"/>
      <zone data="#m0_k457_003" lrx="509" lry="926" type="measure" ulx="400" uly="122" xml:id="zoneOf_m0_k457_003"/>
    </surface>
  </facsimile>
  <music>
    <body>
      <mdiv n="1" xml:id="mdiv_486">
        <score xml:id="score_492">
          <scoreDef key.mode="minor" key.pname="c" key.sig="3f" meter.count="3" meter.unit="4" xml:id="scoreDef_01">
            <staffGrp bar.thru="true" symbol="brace" xml:id="staffGrp_01">
              <staffDef clef.line="2" clef.shape="G" lines="5" n="1" xml:id="staffDef_P1"/>
              <staffDef clef.line="4" clef.shape="F" lines="5" n="2" xml:id="staffDef_P2"/>
            </staffGrp>
          </scoreDef>
          <section xml:id="section_A_m1-1">
            <measure n="1" xml:id="m1">
              <staff n="1" xml:id="staff_534">
                <layer n="1" xml:id="layer_540">
                  <note accid.ges="f" dots="1" dur="2" oct="5" pname="e" tstamp="1" xml:id="note_546"/>
                </layer>
              </staff>
              <staff n="2" xml:id="staff_552">
                <layer n="1" xml:id="layer_558">
                  <mRest tstamp="1" xml:id="mRest_564"/>
                </layer>
              </staff>
              <dynam staff="1" tstamp="1" xml:id="dynam_570">cresc.</dynam>
            </measure>
          </section>
        </score>
      </mdiv>
    </body>
  </music>
</mei>
```
Or download any file from https://dme.mozarteum.at/movi/

**Comment by wergo** [comment]
Thanks for reporting these issues, @o-sapov.  

`mei-friend` relies on Verovio to manipulate the MEI encoding. In "normal mode" (that's the slower default mode), it reads the entire MEI code into Verovio, sets the changes there (i.e. invert placement of directive) and reads the MEI code from Verovio to display it in the editor. Through this, the entire MEI code looks as defined through the output method from Verovio (`MEIOutput::Export`, thus, using a hardcoded schema URL, resolving HTML entities, ignoring non-standard facsimile, and changing the order of attributes and the trailing zeros in time stamps). 

In "speed mode" (currently only for System and System/Page breaks option, to be extended to all breaks options later), MEI-friend will change only the relevant excerpt of the MEI encoding through a DOM representation, not the entire file. However, I see that having the `xml:id`s as last attribute, it currently does not replace the xml properly. This I will fix hopefully soon. However, the trailing zero thing will prevail (see also https://github.com/rism-digital/verovio/issues/975). 

We could raise these issues on https://github.com/rism-digital/verovio.

**Comment by o-sapov** [comment]
As current workaround, I save the non-modified version of `<meiHead>` +  `<facsimile>` externally and then merge `<music> `after I've finished editing the music part. 

Tstamps can be fixed with RegEx:

Integers  like 1.000000
Find: `(tstamp="\d)[.][0]+(")`
Replace: `\1\2`

Floats like 3.500000
Find: `(tstamp="\d[.][1-9]*)[0]+(")`
Replace: ` \1\2`

**Comment by wergo** [comment]
In [0.3.7](https://github.com/trompamusic/mei-friend/releases/tag/v0.3.7), invert placement (X) should work properly in "speed mode" on your files, without altering the other parts. (The attribute order and trailing zero issues still prevail.)

**Comment by o-sapov** [comment]
Yes, just tested it with 0.3.8.
